BEGIN;

CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  email TEXT UNIQUE,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  guest BOOLEAN DEFAULT 1 CHECK (guest IN (0, 1))
);

CREATE TABLE IF NOT EXISTS sessions (
  id TEXT PRIMARY KEY,
  user_id INTEGER REFERENCES users(id),
  expires_at DATETIME NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS packs (
  id TEXT PRIMARY KEY,
  user_id INTEGER REFERENCES users(id),
  title TEXT DEFAULT 'Your pack',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS items (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER REFERENCES users(id),
  name TEXT NOT NULL,
  weight INTEGER NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(name, user_id)
);

CREATE TABLE IF NOT EXISTS packs_items (
  pack_id TEXT REFERENCES packs(id),
  item_id TEXT REFERENCES items(id),
  quantity INTEGER DEFAULT 1
);

COMMIT;

PRAGMA foreign_keys = ON;